export const MARKET_GET_REQUEST = "MARKET_GET_REQUEST";
export const MARKET_GET_SUCCESS = "MARKET_GET_SUCCESS";
export const MARKET_GET_FAIL = "MARKET_GET_FAIL";

export const CREATE_MARKET_FAIL = "CREATE_MARKET_FAIL";
export const CREATE_MARKET_REQUES = "CREATE_MARKET_REQUES";
export const CREATE_MARKET_SUCCESS = "CREATE_MARKET_SUCCESS";

export const MARKETS_PENDING_GET_REQUEST="MARKETS_PENDING_GET_REQUEST"
export const MARKETS_PENDING_GET_FAIL="MARKETS_PENDING_GET_FAIL"
export const MARKETS_PENDING_GET_SUCCESS = "MARKETS_PENDING_GET_SUCCESS"

export const MARKET_PENDING_GET_REQUEST="MARKET_PENDING_GET_REQUEST"
export const MARKET_PENDING_GET_FAIL="MARKET_PENDING_GET_FAIL"
export const MARKET_PENDING_GET_SUCCESS = "MARKET_PENDING_GET_SUCCESS"

export const MARKET_PENDING_DELETE_REQUEST="MARKET_PENDING_DELETE_REQUEST"
export const MARKET_PENDING_DELETE_FAIL="MARKET_PENDING_DELETE_FAIL"
export const MARKET_PENDING_DELETE_SUCCESS = "MARKET_PENDING_DELETE_SUCCESS"

export const MARKET_PENDING_LIVE_REQUEST="MARKET_PENDING_LIVE_REQUEST"
export const MARKET_PENDING_LIVE_FAIL="MARKET_PENDING_LIVE_FAIL"
export const MARKET_PENDING_LIVE_SUCCESS = "MARKET_PENDING_LIVE_SUCCESS"